[server]
headless = true
address = "0.0.0.0"
port = 5000
runOnSave = true
allowRunOnSave = true
maxUploadSize = 1000

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"